Bookstore5/Components/CartSummaryViewComponent.cs
using Bookstore5.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookstore5.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Bookstore5/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bookstore5.Models;

namespace Bookstore5.Components
{
    public class NavigationMenuViewComponent : ViewComponent //needs to be called viewComponent unless you die.
    {
        private IBookstoreRepository repository;

        public NavigationMenuViewComponent (IBookstoreRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke() //make a partial view and drop it on the index page so it can spread its goodness to the world
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"]; //this is how we will dynamically highlight the buttons. The viewbag lets us pass the data as to what page we are on back and forth. It is like global variable, except...not
            return View(repository.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

//let us take note, that the folder to the left that holds the appropriate view is called NavigationMenu. This may look familiar, as this file is named similarly. Please remember that computers are idiots, and it needs to look at the right folder--the folder named like this file--to bring out the correct view. Silly computer! You dumb.

Bookstore5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> <!--import bootstrap-->
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">THIS IS A STORE FOR BOOKS...WITH PAGES...PHYSICAL PAGES...THE ONES YOU READ WITH YOUR EYES AND BRAIN...BUT NOT ON A SCREEN...THESE ARE NOT DIGITAL THEY ARE REAL BOOKS</div>
                <div class="col-12 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <vc:navigation-menu /> <!--this the view componenet found in the components page. It's kinda like a partial view, except not really. To tell the truth, I don't know the difference besides that this has ViewComponent at the end of its name-->

    </div>
    <div class="container">

        <main role="main" class="pb-3">


            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>