Bookstore5/Pages/Buy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Bookstore5.Models;
using Bookstore5.Infrastructure;

namespace Bookstore5.Pages
{
    public class BuyModel : PageModel
    {
        private IBookstoreRepository repository;

        public BuyModel (IBookstoreRepository repo, Cart cartService)
        {
            repository = repo;
            Cart = cartService;
        }

        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
//            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        public  IActionResult OnPost(long bookId, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(b => b.BookId == bookId);
//            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.AddItem(book, 1);
//            HttpContext.Session.SetJson("cart", Cart);
            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(long bookId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
                cl.Book.BookId == bookId).Book);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Bookstore5/Pages/Buy.cshtml
@page
@model Bookstore5.Pages.BuyModel
@{
    // this is an MVVM (Model, View, ViewModel) method of building web pages UNLIKE MVC (Model, View, Controller). RazorPages are self-contained and do routing internally. This is still not the most common method, but probably will be in the future.
}

<h2>Your Cart</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Project</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
        </tr>

    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines) //pull cart lines
        {
            <tr>
                <td>@line.Book.Title</td>
                <td>@line.Quantity</td>
                <td>$@line.Book.Price</td>
                <td>$@(line.Quantity * line.Book.Price)</td>
                <td class="text-black-50 text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="BookId"
                               value="@line.Book.BookId" />
                        <input type="hidden" name="returnUrl"
                               value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.Cart.ComputeTotalSum().ToString("c")</td> <!--Calculates the total sum and uses the ToString function to make it currency-->
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>